server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
 
  jpa:
    hibernate:
      ddl-auto: create-drop #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 129748179435-v17tfrbr1io0bmrbgqkbu3t19l8i9t1h.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            